### ISSUE TITLE
Handle empty files

### ISSUE THREAD

**Issue by creideiki** [saab-simc-admin/palletjack#128]
When Pallet Jack encounters a file that does not contain any data (e.g. because the entire contents have been commented out for debugging), the entire warehouse fails to load with the following error message:
```
irb(main):001:0> PalletJack.load('.')
NoMethodError: undefined method `to_hash' for nil:NilClass
        from /home/creideiki/.gem/ruby/gems/kvdag-0.1.5/lib/kvdag/attrnode.rb:55:in `merge!'
        from /home/creideiki/.gem/ruby/gems/palletjack-0.7.1/lib/palletjack/pallet.rb:41:in `block in load'
        from /home/creideiki/.gem/ruby/gems/palletjack-0.7.1/lib/palletjack/pallet.rb:34:in `foreach'
        from /home/creideiki/.gem/ruby/gems/palletjack-0.7.1/lib/palletjack/pallet.rb:34:in `load'
        from /home/creideiki/.gem/ruby/gems/palletjack-0.7.1/lib/palletjack/pallet.rb:16:in `load'
        from /home/creideiki/.gem/ruby/gems/palletjack-0.7.1/lib/palletjack/warehouse.rb:62:in `pallet'
        from /home/creideiki/.gem/ruby/gems/palletjack-0.7.1/lib/palletjack/warehouse.rb:39:in `block (2 levels) in load'
        from /home/creideiki/.gem/ruby/gems/palletjack-0.7.1/lib/palletjack/warehouse.rb:36:in `foreach'
        from /home/creideiki/.gem/ruby/gems/palletjack-0.7.1/lib/palletjack/warehouse.rb:36:in `block in load'
        from /home/creideiki/.gem/ruby/gems/palletjack-0.7.1/lib/palletjack/warehouse.rb:32:in `foreach'
        from /home/creideiki/.gem/ruby/gems/palletjack-0.7.1/lib/palletjack/warehouse.rb:32:in `load'
        from /home/creideiki/.gem/ruby/gems/palletjack-0.7.1/lib/palletjack/warehouse.rb:16:in `load'
        from /home/creideiki/.gem/ruby/gems/palletjack-0.7.1/lib/palletjack.rb:7:in `load'
        from (irb):1
        from /usr/bin/irb:12:in `<main>'
```
Handle this case more gracefully.

**Comment by notCalle** [comment]
Something similar probably happens for any file that is not interpreted as a hash by the YAML loader.
How do we want to handle such data corruption? Silently dropping corrupt boxes is dangerous.

**Comment by creideiki** [comment]
I did some experiments:
* A file without a YAML document (either empty or just comments) returns `false`.
* A file with a syntactically incorrect YAML document throws `Psych::SyntaxError`.
* Proper boxes are hashes.
* `transforms.yaml` is a list.

I can see a use for allowing empty files, so I would suggest replacing `false` with `{}`. Maybe do that substitution, and then throw a syntax error (naming the problematic box) if the result isn't a hash?

**Comment by creideiki** [comment]
And also add this patch, to make the traceable YAML parser output file names in its exceptions:
```ruby
diff --git a/lib/traceable.rb b/lib/traceable.rb
index fd6b3d7..2fae757 100644
--- a/lib/traceable.rb
+++ b/lib/traceable.rb
@@ -1,3 +1,4 @@
+# -*- coding: utf-8 -*-
 require 'psych'
 
 # Read YAML files and remember where each value came from.
@@ -193,7 +194,7 @@ module TraceableYAML
     handler = PositionHandler.new(tag)
     parser = Psych::Parser.new(handler)
     handler.parser = parser
-    parser.parse doc
+    parser.parse(doc, tag)
     if PositionVisitor.respond_to?(:create)
       # Ruby 2.1 and above
       visitor = PositionVisitor.create
```

**Comment by notCalle** [comment]
Sounds reasonable. Also, add more test cases.

**Comment by creideiki** [comment]
Code written (in [creideiki:yaml-reader-128](https://github.com/creideiki/palletjack/tree/yaml-reader-128)), but testing it is annoying. Pallets really don't want to exist by themselves, and I don't want to create an entire (admittedly tiny) warehouse for each test case.
